OSPJ File Storage/Controllers/ManageAccountController.cs
using OSPJ_File_Storage.Models;
using System.Web.Mvc;

namespace OSPJ_File_Storage.Controllers
{
    public class ManageAccountController : Controller
    {
        // GET: ManageAccount
        public ActionResult MAccount()
        {
            return View();
        }

        [Route("Register")]
        [HttpPost]
        public ActionResult Register(RegisterModel registerModel)
        {
            Database db = new Database();

            if (registerModel.Password != registerModel.CPassword)
            {
                ViewData["RegisterMessage"] = "Password does not match !";
                return View("~/views/manageaccount/MAccount.cshtml");
            }

            if (db.UserIsRegistered(registerModel))
            {
                ViewData["RegisterMessage"] = "Username already registered !";
                return View("~/views/manageaccount/MAccount.cshtml");
            }

            db.RegisterUser(registerModel);
            ViewData["RegisterMessage"] = "Registration Successful !";
            return View("~/views/manageaccount/MAccount.cshtml");
        }

        [Route("ResetTwoFA")]
        [HttpPost]
        public ActionResult ResetTwoFA(ResetTwoFAModel resetTwoFAModel)
        {
            Database db = new Database();

            if (!db.UsernameExist(resetTwoFAModel.Username))
            {
                ViewData["Reset2FAMessage"] = "Username does not exist !";
                return View("~/views/manageaccount/MAccount.cshtml");
            }

            db.Reset2FA(resetTwoFAModel);

            ViewData["Reset2FAMessage"] = "2FA reset successfully !";
            return View("~/views/manageaccount/MAccount.cshtml");
        }

        [Route("ResetPassword")]
        [HttpPost]
        public ActionResult ResetPassword(ResetPasswordModel resetPasswordModel)
        {
            Database db = new Database();

            if (!db.UsernameExist(resetPasswordModel.Username))
            {
                ViewData["ResetPasswordMessage"] = "Username does not exist !";
                return View("~/views/manageaccount/MAccount.cshtml");
            }

            db.ResetPassword(resetPasswordModel);

            ViewData["ResetPasswordMessage"] = "Password reset successfully !";
            return View("~/views/manageaccount/MAccount.cshtml");
        }
    }
}

OSPJ File Storage/Views/ManageAccount/MAccount.cshtml
@{
    ViewBag.Title = "MAccount";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/Content/ManageAccount.css" />
</head>

<body>

    <div class="Register">
        <h4><u>Registration</u></h4><br />
        @using (Html.BeginForm("Register", "ManageAccount", FormMethod.Post))
        {
            <label for="fname">First name: </label><input type="text" id="fname" name="fname"><br><br>
            <label for="lname">Last name: </label><input type="text" id="lname" name="lname"><br><br>
            <label for="username">Username: </label><input type="text" id="username" name="username"><br><br>
            <label for="password">Password: </label><input type="password" id="password" name="password"><br><br>
            <label for="RPasssword">Retype Password: </label><input type="password" id="cpassword" name="cpassword"><br><br>
            <input type="submit" value="Submit">
        }
        <hr />
        @ViewData["RegisterMessage"]
    </div>

    <div class="ResetOTP">
        <h4><u>Reset 2FA</u></h4><br />
        @using (Html.BeginForm("ResetTwoFA", "ManageAccount", FormMethod.Post))
        {
            <label for="Username">Username: </label><input type="text" id="username" name="username"><br><br>
            <input type="submit" value="Submit">
        }
        <hr />
        @ViewData["Reset2FAMessage"]
    </div>
    <div class="ResetPassword">
        <h4><u>Reset Password</u></h4><br />
        @using (Html.BeginForm("ResetPassword", "ManageAccount", FormMethod.Post))
        {
            <label for="Username">Username: </label><input type="text" id="username" name="username"><br><br>
            <label for="Password">Password: </label><input type="password" id="password" name="password"><br><br>
            <input type="submit" value="Submit">
        }
        <hr />
        @ViewData["ResetPasswordMessage"]
    </div>
</body>
</html>