OSPJ File Storage/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Diagnostics;
using System.Linq;
using System.Web;
using System.Web.Mvc;

// manually added References
using OSPJ_File_Storage.Models;
using WUApiLib;

namespace OSPJ_File_Storage.Controllers
{
    public class AdminController : Controller
    {
        static string constr = ("Data Source =192.168.1.82;User ID =sa; Password=password;Initial Catalog = UserAccounts;");

        private Asset Assets = new Asset();
        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Dashboard()
        {
            return View();
        }

       public ActionResult ViewAssets()
        {
            return View();
        }

        public void CheckAssets()
        {
            ISearchResult results = Assets.SearchUpdates();
            Response.Write("ohh checking local updates has been triggered? is it working properly tho?hehe");
            Debug.WriteLine("ohh checking local updates has been triggered? is it working properly tho?");

            foreach (IUpdate x in results.Updates)
            {
                Debug.WriteLine(results.Updates.Count);
                Debug.WriteLine("Searcher returend this " + x.Title);
                Response.Write(x.Title);
            }
        }

        public ActionResult ViewSpecificAsset(string ipAddress)
        {
            Asset selectedAsset = new Asset();
         // Assets.SearchRemoteUpdates();
            selectedAsset = Assets.GetAssetConfig(ipAddress);
            ViewBag.message = selectedAsset;
            return View();
        }

        public void uninstall(string ipAddress, string uninstallCommand)
        {
            Assets.UninstallProgram(ipAddress, uninstallCommand);
        }


        //ERROR OCCURING HERE WHEN TRYING SQL COMMANDS
        public List<Asset> GetAllAssets()
        {
            List<Asset> RetrievedAssets = new List<Asset>();
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "SELECT * FROM tblFiles";
                    cmd.Connection = con;
                    con.Open();
                    cmd.ExecuteReader();
                }
            }
            return null;
        }

       
    }
}

OSPJ File Storage/Controllers/FileShareController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO;
using System.Configuration;
using System.Data.SqlClient;
using OSPJ_File_Storage.Models;
using System.Security.Cryptography;
using System.Text;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Data;

namespace OSPJ_File_Storage.Controllers
{
    public class FileShareController : Controller
    {
        // GET: FileShare
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult StoredFiles()
        {
            return View();
        }

        public ActionResult UploadFile()
        {
            return View();
        }

        public ActionResult MyFiles()
        {
            return View();
        }

       
        public ActionResult UploadFileH()
        {
            return View();
        }

        public ActionResult StoredFilesH()
        {
            return View();
        }

        //UPLOAD AND DOWNLOAD 
        
        SqlConnection con;
        
       



       
        

        public int CheckId()
        {
            con = new SqlConnection(constrLog);
            string sql = "select count(*) from [logs]";
            SqlCommand c = new SqlCommand(sql, con);
            int temp = Convert.ToInt32(c.ExecuteScalar().ToString());
            temp++;
            con.Close();
            return temp;
        }
        //test
        public void DlLog()
        {
            con = new SqlConnection(constrLog);
            con.Open();
            SqlCommand sc = new SqlCommand("SELECT * FROM [Logs]", con);
            SqlDataAdapter da = new SqlDataAdapter(sc);
            DataSet ds = new DataSet();
            da.Fill(ds);

            ds.WriteXml("MyFile.txt");

            con.Close();
        }

        //shr
        // GET: UploadFile
        static string password = "ThePasswordToDecryptAndEncryptTheFile";

        static int id = 1;
        static String constr = @"Data Source=192.168.1.82; User ID=sa;Password=password; Initial Catalog=HoneyUpload";
        static String constrLog = @"Data Source=192.168.1.82; User ID=sa;Password=password;Initial Catalog=HoneyLogs";


        [HttpPost]
        public ActionResult Index(HttpPostedFileBase postedFile)
        {

            if (postedFile != null)
            {
                string path = Server.MapPath("~/Uploads/");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                postedFile.SaveAs(path + Path.GetFileName(postedFile.FileName));
                ViewBag.Message = "File uploaded successfully.";
                FileEncrypt(path + Path.GetFileName(postedFile.FileName));
                //
                using (SqlConnection con = new SqlConnection(constrLog))
                {
                    using (SqlCommand cmd = new SqlCommand())
                    {
                        cmd.CommandText = "Insert into [Logs] values ('" + CheckId() + "','" + DateTime.Now.ToString("MM/dd/yyyy hh:mm tt") + "','upload','testfilename.txt'";
                        cmd.Connection = con;
                        con.Open();
                        cmd.ExecuteScalar();
                        //
                    }




                    return View(GetFiles());
                }
            }

            else
            {
                Debug.WriteLine("No File Chosen");
                return null;
            }
        }

        [HttpPost]
        public FileResult DownloadFile(int? fileId)
        {
            byte[] bytes;
            string fileName, contentType;
            using (SqlConnection con = new SqlConnection(constrLog))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "Insert into [Logs] values ('" + CheckId() + "','" + DateTime.Now.ToString("MM/dd/yyyy hh:mm tt") + "','Download','testfilename.txt'";
                    cmd.Connection = con;
                    con.Open();
                    cmd.ExecuteScalar();

                }
            }
                using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand())
                {
                    cmd.CommandText = "SELECT Name, Data, ContentType FROM fakefiles WHERE Id=@Id";
                    cmd.Parameters.AddWithValue("@Id", fileId);
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        sdr.Read();
                        bytes = (byte[])sdr["Data"];
                        contentType = sdr["ContentType"].ToString();
                        fileName = sdr["Name"].ToString();
                    }

                    string path = Server.MapPath("~/Downloads/");
                    if (!Directory.Exists(path))
                    {
                        Directory.CreateDirectory(path);
                        //String decrypted = FileDecrypt(Path.GetFileName(fileName), path + Path.GetFileName(fileName) + "decrypted", password).Name;
                        return File(bytes, contentType, fileName);

                    }
                    //String decrypted1 = FileDecrypt(fileNamepath + Path.GetFileName(fileName) + "decrypted", password).Name;
                    //  con.Close();
                    return File(bytes, contentType, fileName);

                }
            }

        }
            

        private static List<FileModel> GetFiles()
        {
            List<FileModel> files = new List<FileModel>();
            using (SqlConnection con = new SqlConnection(constr))
            {
                using (SqlCommand cmd = new SqlCommand("SELECT Id, Name FROM fakefiles"))
                {
                    cmd.Connection = con;
                    con.Open();
                    using (SqlDataReader sdr = cmd.ExecuteReader())
                    {
                        while (sdr.Read())
                        {
                            files.Add(new FileModel
                            {
                                Id = Convert.ToInt32(sdr["Id"]),
                                Name = sdr["Name"].ToString()
                            });
                        }
                    }
                    con.Close();
                }
            }
            return files;
        }
        //  Call this function to remove the key from memory after use for security
        [DllImport("KERNEL32.DLL", EntryPoint = "RtlZeroMemory")]
        public static extern bool ZeroMemory(IntPtr Destination, int Length);

        /// <summary>
        /// Creates a random salt that will be used to encrypt your file. This method is required on FileEncrypt.
        /// </summary>
        /// <returns></returns>
        public static byte[] GenerateRandomSalt()
        {
            byte[] data = new byte[32];

            using (RNGCryptoServiceProvider rng = new RNGCryptoServiceProvider())
            {
                for (int i = 0; i < 10; i++)
                {
                    // Fille the buffer with the generated data
                    rng.GetBytes(data);
                }
            }

            return data;
        }

        /// <summary>
        /// Encrypts a file from its path and a plain password.
        /// </summary>
        /// <param name="inputFile"></param>
        /// <param name="password"></param>
        private void FileEncrypt(string inputFile)
        {
            //http://stackoverflow.com/questions/27645527/aes-encryption-on-large-files

            //generate random salt
            byte[] salt = GenerateRandomSalt();

            //create output file name
            FileStream fsCrypt = new FileStream(inputFile + ".aes", FileMode.Create);



            //convert password string to byte arrray
            byte[] passwordBytes = System.Text.Encoding.UTF8.GetBytes(password);

            //Set Rijndael symmetric encryption algorithm
            RijndaelManaged AES = new RijndaelManaged();
            AES.KeySize = 256;
            AES.BlockSize = 128;
            AES.Padding = PaddingMode.PKCS7;

            //http://stackoverflow.com/questions/2659214/why-do-i-need-to-use-the-rfc2898derivebytes-class-in-net-instead-of-directly
            //"What it does is repeatedly hash the user password along with the salt." High iteration counts.
            var key = new Rfc2898DeriveBytes(passwordBytes, salt, 50000);
            AES.Key = key.GetBytes(AES.KeySize / 8);
            AES.IV = key.GetBytes(AES.BlockSize / 8);

            //Cipher modes: http://security.stackexchange.com/questions/52665/which-is-the-best-cipher-mode-and-padding-mode-for-aes-encryption
            AES.Mode = CipherMode.CFB;

            // write salt to the begining of the output file, so in this case can be random every time
            fsCrypt.Write(salt, 0, salt.Length);

            CryptoStream cs = new CryptoStream(fsCrypt, AES.CreateEncryptor(), CryptoStreamMode.Write);

            FileStream fsIn = new FileStream(inputFile, FileMode.Open);

            //create a buffer (1mb) so only this amount will allocate in the memory and not the whole file
            byte[] buffer = new byte[1048576];
            int read;

            try
            {
                while ((read = fsIn.Read(buffer, 0, buffer.Length)) > 0)
                {

                    cs.Write(buffer, 0, read);
                }

                // Close up
                fsIn.Close();
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error: " + ex.Message);
            }
            finally
            {
                cs.Close();
                fsCrypt.Close();
            }

OSPJ File Storage/Controllers/LoginController.cs
using OSPJ_File_Storage.Models;
using System;
using System.Diagnostics;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNetCore.Totp;

namespace OSPJ_File_Storage.Controllers
{
    public class LoginController : Controller
    {
        //This controller is designed for creating&destroying login sessions.

        // GET: Login
        
        public ActionResult LoginPage()
        {
            return View();
        }

        public ActionResult OTPVerify()
        {
            return View();
        }

        public ActionResult ResetPassword()
        {
            return View();
        }

        public ActionResult Logout()
        {
            Session.Remove("User");
            return View("~/views/home/index.cshtml");
        }

        
        [Route("LoginSubmit")]
        [HttpPost]
        public ActionResult LoginSubmit(LoginFormModel loginFormModel)
        {
            if (loginFormModel.Username == null)
            {
                ViewData["ErorMessage"] = "Username is required";
                return View("~/views/Login/LoginPage.cshtml");
            }
            Database db = new Database();
            bool loginSuccessful = db.CheckLoginIsSuccessful(loginFormModel);
            bool userExist = db.CheckUserExist(loginFormModel);
            Debug.WriteLine(userExist);

            if (!loginSuccessful)
            {
                if (userExist == true)
                {
                    int failcount = db.CheckFailCount(loginFormModel);
                    if (failcount > 4)
                    {
                        //Direct to honey pot page
                        return View("~/Views/Home/DefaultHomePageH.cshtml");
                    }
                    else
                    {
                        failcount++;
                        Debug.WriteLine(failcount);
                        db.UpdateFailCount(loginFormModel, failcount);
                        ViewData["ErorMessage"] = "Login failed, invalid username/password";
                        return View("~/views/Login/LoginPage.cshtml");
                    }
                }
                else
                ViewData["ErorMessage"] = "Login failed, invalid username/password";
                return View("~/views/Login/LoginPage.cshtml");
                
                
            }

            // if login successful, set user session
            Session["User"] = loginFormModel.Username;
            db.UpdateFailCount(loginFormModel, 0);
            // and check if user has setup 2 FA

            bool userSetuped2FA = db.CheckIfUserSetUp2FA(loginFormModel);

            if (userSetuped2FA)
            {
                return View("~/views/Login/LoginWith2FA.cshtml");
            }
            else
            {
                var totpSetupGenerator = new TotpSetupGenerator();
                var totpSetup = totpSetupGenerator.Generate("FileShareApp", Session["User"].ToString(), "YourSuperSecretKeyHere" + Session["User"], 300, 300);

                // generate QRcode and put inside viewdata to display
                ViewData["QRImage"] = totpSetup.QrCodeImage;
                ViewData["ManualSetupKey"] = totpSetup.ManualSetupKey;

                return View("~/views/Login/Setup2fa.cshtml");
            }
        }

        [Route("Submit2FAComplete")]
        [HttpPost]
        public ActionResult Submit2FAComplete()
        {
            Database db = new Database();
            db.Completed2FASetup(Session["User"].ToString());

            
            return View("~/views/Home/index.cshtml");
        }

        [Route("Check2FAPin")]
        [HttpPost]
        public ActionResult Check2FAPin(Google2FAModel google2FModel)
        {
            var totpValidator = new TotpValidator(new TotpGenerator());
            bool isCorrectPIN = totpValidator.Validate("YourSuperSecretKeyHere" + Session["User"], Convert.ToInt32(google2FModel.Pin));

            if (isCorrectPIN  )
            {
                return View("~/views/Home/index.cshtml");

            }
            else
            {
                ViewData["ErorMessage"] = "Invalid Pin!";
                return View("~/views/Login/LoginWith2FA.cshtml");
            }
        }
    }
}

OSPJ File Storage/Views/Login/Hello.cshtml
@{
   Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
        <h1>Hello</h1>
    
    </div>
</body>
</html>

OSPJ File Storage/Views/Login/HelloWorld.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>
    <h1>Sourcetree Working?</h1>
    </div>
</body>
</html>

OSPJ File Storage/Views/Login/LoginPage.cshtml
@{
    Layout = null;
}
@{
    ViewBag.Title = "LoginPage";
}
<html>
<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="au theme template">
    <meta name="author" content="Hau Nguyen">
    <meta name="keywords" content="au theme template">

    <!-- Title Page-->
    <title>Login</title>

    <!-- Fontfaces CSS-->
    <link href="~/Content/Template1/css/font-face.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

    <!-- Bootstrap CSS-->
    <link href="/Content/Template1/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

    <!-- Vendor CSS-->
    <link href="/Content/Template1/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/wow/animate.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/slick/slick.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/select2/select2.min.css" rel="stylesheet" media="all">
    <link href="/Content/Template1/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="/Content/LoginPage.css" rel="stylesheet" media="all">

</head>

<body class="animsition">
<<<<<<< HEAD
    <div class="card card-container">
        <h2 class='login_title text-center'>Login Panel</h2>
        <hr>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div class="panel panel-default">
                        <div class="panel-body ">
                            @using (Html.BeginForm("LoginSubmit", "Login", FormMethod.Post))
                            {
                                <fieldset>
=======

    <div class="page-wrapper">
        <div class="page-content--bge5">
            <div class="container">
                <div class="login-wrap">
                    <div class="login-content">
                        <div class="login-logo">
                            <a href="#">
                                <img src="/Content/Template1/images/icon/logo.png" alt="CoolAdmin">
                            </a>
                        </div>
                        <div class="login-form">
                            <fieldset>
                                <form action="" method="post">
>>>>>>> Naushad
                                    <div class="form-group">
                                        <label>Email Address</label>
                                        <input class="au-input au-input--full" type="email" name="email" placeholder="Email">
                                    </div>
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input class="au-input au-input--full" type="password" name="password" placeholder="Password">
                                    </div>
                                    <div class="login-checkbox">
                                        <label>
                                            <input type="checkbox" name="remember">Remember Me
                                        </label>
                                        <label>
                                            <a href="#">Forgotten Password?</a>
                                        </label>
                                    </div>
                                    @using (Html.BeginForm("MyFiles", "FileShare", FormMethod.Post))
                                    {
                                        <button class="au-btn au-btn--block au-btn--green m-b-20" type="submit">sign in</button>
                                    }

                                    @using (Html.BeginForm("MyFiles", "FileShare", FormMethod.Post))
                                    {
                                        <button type="submit">Testing</button>
                                    }

                                    @using (Html.BeginForm("Dashboard", "Admin", FormMethod.Post))
                                    {
                                        <button type="submit">Login to admin </button>
                                    }
                                    <div class="social-login-content">
                                        <div class="social-button">
                                            <button class="au-btn au-btn--block au-btn--blue m-b-20">sign in with facebook</button>
                                            <button class="au-btn au-btn--block au-btn--blue2">sign in with twitter</button>
                                        </div>
                                        </div>
                                        <input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
                                </form>
                            </fieldset>
                                    
                            
                        </div>
                        <p style="color:red;" class="text-center">@ViewData["ErorMessage"]</p>
                    </div>
                </div>
            </div>
        </div>

    </div><!-- /card-container -->

    <!-- Jquery JS-->
    <script src="/Content/Template1/vendor/jquery-3.2.1.min.js"></script>
    <!-- Bootstrap JS-->
    <script src="/Content/Template1/vendor/bootstrap-4.1/popper.min.js"></script>
    <script src="/Content/Template1/vendor/bootstrap-4.1/bootstrap.min.js"></script>
    <!-- Vendor JS       -->
    <script src="/Content/Template1/vendor/slick/slick.min.js"></script>
    <script src="/Content/Template1/vendor/wow/wow.min.js"></script>
    <script src="/Content/Template1/vendor/animsition/animsition.min.js"></script>
    <script src="/Content/Template1/vendor/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
    <script src="/Content/Template1/vendor/counter-up/jquery.waypoints.min.js"></script>
    <script src="/Content/Template1/vendor/counter-up/jquery.counterup.min.js"></script>
    <script src="/Content/Template1/vendor/circle-progress/circle-progress.min.js"></script>
    <script src="/Content/Template1/vendor/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="/Content/Template1/vendor/chartjs/Chart.bundle.min.js"></script>
    <script src="/Content/Template1/vendor/select2/select2.min.js"></script>

    <!-- Main JS-->
    <script src="/Content/Template1/js/main.js"></script>

    </body>
</html>
<!-- end document-->

OSPJ File Storage/Views/Login/LoginWith2FA.cshtml
@{
    Layout = null;
}
@{
    ViewBag.Title = "2FA";
}

    <head>
        <!-- Required meta tags-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="au theme template">
        <meta name="author" content="Hau Nguyen">
        <meta name="keywords" content="au theme template">

        <!-- Title Page-->
        <title>Login</title>

        <!-- Fontfaces CSS-->
        <link href="~/Content/Template1/css/font-face.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/font-awesome-4.7/css/font-awesome.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/font-awesome-5/css/fontawesome-all.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/mdi-font/css/material-design-iconic-font.min.css" rel="stylesheet" media="all">

        <!-- Bootstrap CSS-->
        <link href="/Content/Template1/vendor/bootstrap-4.1/bootstrap.min.css" rel="stylesheet" media="all">

        <!-- Vendor CSS-->
        <link href="/Content/Template1/vendor/animsition/animsition.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/bootstrap-progressbar/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/wow/animate.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/css-hamburgers/hamburgers.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/slick/slick.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/select2/select2.min.css" rel="stylesheet" media="all">
        <link href="/Content/Template1/vendor/perfect-scrollbar/perfect-scrollbar.css" rel="stylesheet" media="all">

        <!-- Main CSS-->
        <link href="/Content/LoginPage.css" rel="stylesheet" media="all">

    </head>

<div class="card card-container">
    <h2 class='login_title text-center'>Login With 2FA</h2>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-md-4 col-md-offset-4">
                <div class="panel panel-default">
                    <div class="panel-body">
                        @using (Html.BeginForm("Check2FAPin", "Login", FormMethod.Post))
                        {
                            <fieldset>
                                <div class="form-group">
                                    <input class="form-control" placeholder="Google 2FA PIN" name="Pin" type="number">
                                </div>
                                <input class="btn btn-lg btn-success btn-block" type="submit" value="Authnticate 2FA Pin">
                            </fieldset>
                        }
                    </div>
                    <p style="color:red;" class="text-center">@ViewData["ErorMessage"]</p>
                </div>
            </div>
        </div>
    </div>
</div><!-- /card-container -->

OSPJ File Storage/Views/Login/OTPVerify.cshtml
@{
    ViewBag.Title = "OTPVerify";
}

<h2>OTPVerify</h2>

OSPJ File Storage/Views/Login/ResetPassword.cshtml
@{
    ViewBag.Title = "ResetPassword";
}

<h2>ResetPassword</h2>

OSPJ File Storage/Views/Login/Setup2FA.cshtml
<div class="card card-container">
    <h2 class='login_title text-center'>Setup First Time Login</h2>
    <hr>
    <div class="container">
        <div class="row">
            <h2>Setup 2FA with Google Authenticator App</h2>
            <hr />
            <h4>Scan QR Code</h4>
            <img src="@ViewData["QRImage"]" />
            <h4>Or by using Manual Setup Key</h4>
            @ViewData["ManualSetupKey"]
        </div>
        <hr/>
        @using (Html.BeginForm("Submit2FAComplete", "Login", FormMethod.Post))
        {
            <input class="btn btn-lg btn-success btn-block" type="submit" value="Done Setting Up 2FA">
        }
    </div>
</div><!-- /card-container -->